// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// convolution_body
arma::mat convolution_body(arma::mat dataset, int threshold, arma::vec integers);
RcppExport SEXP ncdDetectTools_convolution_body(SEXP datasetSEXP, SEXP thresholdSEXP, SEXP integersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type integers(integersSEXP);
    __result = Rcpp::wrap(convolution_body(dataset, threshold, integers));
    return __result;
END_RCPP
}
// cumulant
double cumulant(double t, NumericVector p, NumericVector s);
RcppExport SEXP ncdDetectTools_cumulant(SEXP tSEXP, SEXP pSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    __result = Rcpp::wrap(cumulant(t, p, s));
    return __result;
END_RCPP
}
// cumulantD1
double cumulantD1(double t, NumericVector p, NumericVector s);
RcppExport SEXP ncdDetectTools_cumulantD1(SEXP tSEXP, SEXP pSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    __result = Rcpp::wrap(cumulantD1(t, p, s));
    return __result;
END_RCPP
}
// cumulantD2
double cumulantD2(double t, NumericVector p, NumericVector s);
RcppExport SEXP ncdDetectTools_cumulantD2(SEXP tSEXP, SEXP pSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    __result = Rcpp::wrap(cumulantD2(t, p, s));
    return __result;
END_RCPP
}
