// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// convolution_body
arma::mat convolution_body(arma::mat dataset, int threshold, arma::vec integers);
RcppExport SEXP ncdDetectTools_convolution_body(SEXP datasetSEXP, SEXP thresholdSEXP, SEXP integersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type integers(integersSEXP);
    __result = Rcpp::wrap(convolution_body(dataset, threshold, integers));
    return __result;
END_RCPP
}
