# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolution_body <- function(dataset, threshold, integers) {
    .Call('ncdDetectTools_convolution_body', PACKAGE = 'ncdDetectTools', dataset, threshold, integers)
}

